accounts/urls.py
from django.urls import path
from .views import RegisterView, UserLoginView, UserProfileView, UserLogoutView
app_name = 'accounts'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('profile/', UserProfileView.as_view(), name='profile'),
]

home/urls.py
from django.urls import path
from .views import HomeView, VideoDetailView, VideoListView, SearchView, LikeView, DislikeView, LikedVideosView, FilterView
app_name = 'home'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('video/', VideoListView.as_view(), name='video'),
    path('video/detail/<int:pk>', VideoDetailView.as_view(), name='detail'),
    path('search/', SearchView.as_view(), name='search'),
    path('like/<int:pk>/', LikeView.as_view(), name='like'),
    path('dislike/<int:pk>/', DislikeView.as_view(), name='dislike'),
    path('likedvideos/', LikedVideosView.as_view(), name='likedvideos'),
    path('filter/<str:genre>/', FilterView.as_view(), name='filter'),
]

videoplayer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('dashboard/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Add the following line to serve static files during development
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from .managers import UserManager



class CustomUser(AbstractBaseUser, PermissionsMixin):
    """
    An abstract base class implementing a fully featured User model with
    admin-compliant permissions.
    email and password are required. Other fields are optional.
    """

    first_name = models.CharField(_("first name"), max_length=150, blank=False)
    last_name = models.CharField(_("last name"), max_length=150, blank=False)
    email = models.EmailField(_("email address"), unique=True)
    is_staff = models.BooleanField(
        _("staff status"),
        default=False,
        help_text=_("Designates whether the user can log into this admin site."),
    )
    is_active = models.BooleanField(
        _("active"),
        default=True,
        help_text=_(
            "Designates whether this user should be treated as active. "
            "Unselect this instead of deleting accounts."
        ),
    )
    date_joined = models.DateTimeField(_("date joined"), default=timezone.now)
    phone = models.CharField(null=True, blank=True, unique=True, max_length =10)
    profile_picture = models.ImageField(upload_to='userprofile', blank=True, null=True)
    objects = UserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = [ ]


    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = "%s %s" % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def get_profile_pic(self):
        if not self.profile_picture:
            return "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png"
        else:
            return self.profile_picture.url
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        from PIL import Image
        if self.profile_picture:
            img = Image.open(self.profile_picture.path)
            reduced_resolution = (200, 200)
            img.thumbnail(reduced_resolution)
            img.save(self.profile_picture.path)
        

accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from .models import CustomUser


class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'email', 'password1', 'password2']


class LoginForm(AuthenticationForm):
    class Meta:
        model = CustomUser

accounts/views.py
from django.contrib import messages
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import FormView, TemplateView, View

from django.contrib.auth import logout

from home.models import Video

from .forms import RegisterForm
from .models import CustomUser
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import login as auth_login


class RegisterView(FormView):
    template_name = 'accounts/register.html'
    form_class = RegisterForm
    # success_url = 'accounts:login'

    def form_valid(self, form):
        form.save()
        # email = form.cleaned_data.get('email')
        # password = form.cleaned_data.get('password1')
        # user = authenticate(email=email, password=password)
        # login(self.request, user)
        messages.success(self.request, 'Successfully Created Your Account!')
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy('accounts:login')


class UserLoginView(LoginView):
    template_name = 'accounts/login.html'
    success_message = "You were successfully logged in."
    success_url = 'acounts:profile'


    def form_valid(self, form):
        user = form.get_user()
        if user.is_superuser :
            auth_login(self.request, form.get_user())
            messages.success(self.request,'Logged in as a Superuser.')
            return redirect('/admin/')
        # elif  not user.is_verified :
        #     # messages.error(self.request, "Verify Your Email First.")
        #     messages.info(self.request, "You are still under verification.")
        elif user.is_active :
            auth_login(self.request, form.get_user())
            messages.success(self.request,'Logged in successfully.')
            return redirect('accounts:profile')
        else:
            messages.error(self.request, "Something went terribly wrong.")

        # return HttpResponseRedirect(self.get_success_url())
        return self.render_to_response(self.get_context_data(form=form))

    def form_invalid(self, form):
        messages.error(self.request, 'Invalid Username or Password')
        return self.render_to_response(self.get_context_data(form=form))


# Logout View
class UserLogoutView(View):

    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect('accounts:login')


class UserProfileView(TemplateView):
    template_name = 'accounts/profile.html'
    model = CustomUser
    context_object_name = 'user'

    def get_object(self, queryset=None):
        return self.request.user
    

    # Get user activity like commented and liked videos
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['liked_videos'] = Video.objects.filter(like=self.request.user)
        print(context['liked_videos'])
        return context
    

templates/accounts/liked.html
{% extends '../base.html'%}
{% load static %}

{%block titleblock%}Liked Videos{%endblock%}

{%block bodyblock%}
<div class="w-full flex-1 mt-5 px-4 py-5">
    {% for like_video in liked_videos %}
    <div class="w-full space-y-4">
        <h1 class="text-xl font-bold text-neutral-200">
            You Have Liked "<span class="text-red-500 text-2xl">{{liked_videos.count}}</span>" Videos Yet
        </h1>
        <div class="w-full h-auto grid md:grid-cols-4 sm:grid-cols-3 grid-cols-2 md:gap-x-4 gap-x-2 gap-y-6">
            <div
                class="w-full h-auto rounded-md rounded-md overflow-hidden hover:bg-neutral-900/20 cursor-pointer ease-in-out duration-300">
                <a href="#">
                    <div class="w-full h-auto rounded-md overflow-hidden">
                        <img src="{{like_video.video_thumbnail.url}}" alt="video thumbnail"
                            class="w-full aspect-video object-cover object-center transition-all ease-in-out duration-300">
                        <div class="px-2 py-3 space-y-2">
                            <h1
                                class="text-xl font-bold text-neutral-300 cursor-pointer line-clamp-2 text-overflow-ellipsis">
                                {{like_video.title}}
                            </h1>
                            <div class="w-full flex items-center justify-between gap-x-3">
                                <h6 class="text-sm text-neutral-500 font-normal">
                                    Produced by: {{like_video.producer}}
                                </h6>
                                <div class="bg-neutral-900 text-sm text-red-500 rounded-md w-fit px-2 py-1">
                                    {{like_video.age_rating}}
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
    {%empty%}
    <div class="w-full space-y-6 h-auto flex-col py-10 flex items-center justify-center">
        <h1 class="text-3xl font-bold text-neutral-300">
            You Have Not Liked Any Videos Yet
        </h1>
        <a href="{% url 'home:video' %}"
            class="w-fit h-11 px-5 text-base font-semibold bg-red-600 hover:bg-red-500/80 text-neutral-50 rounded-md flex items-center justify-center gap-x-1.5 ease-in-out duration-300">
            <i class="fas fa-film"></i> Explore Movies
        </a>
    </div>
    {% endfor %}
</div>


{%endblock%}

templates/accounts/login.html
{% extends '../base.html'%}
{% load static %}

{%block titleblock%}Login{%endblock%}
{%block bodyblock%}

<div class="w-full h-screen flex-1 flex items-center justify-center mt-10">
    <div class="w-[28%] h-auto py-10 px-8 rounded-xl border-2 border-neutral-900 shadow-md">
        <div class="space-y-2 mb-5">
            <h1 class="text-3xl font-bold text-neutral-100 mb-">Login</h1>
            <p class="text-sm text-neutral-600 font-normal">
                Welcome back! Please enter your details.
            </p>
        </div>
        <form method="post" class="w-full">
            {% csrf_token %}
            {% for field in form %}
            <div class="w-full mb-4 relative">
                <label for="{{ field.id_for_label }}" class="text-base text-neutral-500 font-medium mb-2 block">
                    {{ field.label }}
                </label>
                {{field}}
            </div>
            {% endfor %}

            <div class="w-full flex justify-end">
                <a href="#" class="text-neutral-500 text-sm font-normal hover:text-red-500 ease-out duration-500">
                    Forgot Password?
                </a>
            </div>

            <button type="submit" class="w-full h-11 text-base font-semibold bg-red-600 text-neutral-50 mt-8 rounded-md">
                Login
            </button>

            <p class="text-base text-neutral-600 font-normal mt-7 text-center">
                Don't have an account?
                <a href="{% url 'accounts:register'%}"
                    class="text-decoration-none text-red-500 hover:text-red-600 ease-out duration-300">
                    Register
                </a>
            </p>
        </form>
    </div>
</div>


<script>


    document.addEventListener('DOMContentLoaded', function () {

        // Find the password input
        var passwordInput = document.querySelector('input[type="password"]');
        var email = document.querySelector('#id_username');
        email.placeholder = 'Enter your email'
        email.type = 'email'
        passwordInput.placeholder = 'Enter password'
        email.className = 'w-full h-11 bg-neutral-950 outline-none px-4 text-base placeholder-neutral-700 font-normal rounded-md ring-1 ring-neutral-800 focus:ring-2 focus:ring-red-500 text-neutral-200'
        passwordInput.className = 'w-full h-11 bg-neutral-950 outline-none px-4 text-base placeholder-neutral-700 font-normal rounded-md ring-1 ring-neutral-800 focus:ring-2 focus:ring-red-500 text-neutral-200'

        if (passwordInput) {
            // Create a button element

            var toggleButton = document.createElement('i');
            toggleButton.className = 'fa-solid fa-eye z-30 absolute right-4 top-[3.3rem] -translate-y-1/2 text-neutral-500 cursor-pointer';
            toggleButton.type = 'button';
            toggleButton.addEventListener('click', function () {

                if (passwordInput.type == 'password') {
                    passwordInput.type = 'text'
                    toggleButton.className = 'fa-solid fa-eye-slash z-30 absolute right-4 top-[3.3rem] -translate-y-1/2 text-neutral-500 cursor-pointer';

                }
                else {
                    passwordInput.type = 'password'
                    toggleButton.className = 'fa-solid fa-eye z-30 absolute right-4 top-[3.3rem] -translate-y-1/2 text-neutral-500 cursor-pointer';

                }

            });

            // Create a div to wrap the button
            var buttonWrapper = document.createElement('div');
            buttonWrapper.className = 'input-group-append d-flex justify-content-end';
            buttonWrapper.appendChild(toggleButton);

            // Insert the button wrapper after the password input
            passwordInput.parentNode.insertBefore(buttonWrapper, passwordInput.nextSibling);
        }
    });
</script>



{%endblock%}

templates/accounts/profile.html
{% extends '../base.html'%}
{% load static %}

{%block titleblock%}Profile{%endblock%}
{%block bodyblock%}


<div class="w-full h-auto flex-1 py-3 px-4">
    <!-- Profile data -->
    <div class="w-full h-auto grid grid-cols-3 gap-4">
        <div class="col-span-2 grid grid-cols-4 items-center gap-4 rounded-md p-6 text-neutral-500 font-normal">
            <img src="{{request.user.get_profile_pic}}" alt="profile image"
                class="col-span-1 w-52 h-52 rounded-full border border-neutral-800 p-0.5">
            <div class="col-span-3 text-base space-y-2">
                <h1 class="text-lg font-medium flex items-center text-neutral-400 gap-x-2">
                    <i class="fa-solid fa-user text-sm"></i>
                    {{request.user.get_full_name}}
                </h1>
                <h6 class=" flex items-center gap-x-2">
                    <i class="fa-solid fa-envelope text-sm"></i>
                    {{request.user.email}}
                </h6>
                <!-- <p class="bio line-clamp-2 text-overflow-hidden flex items-center gap-x-2">
                    <i class="text-sm fa-solid fa-edit"></i>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat, delectus.
                </p> -->
                <p class="font-thin flex items-center gap-x-2">
                    <i class="text-sm fa-solid fa-clock"></i>
                    Joined in: {{request.user.date_joined |date:"F Y"}}
                </p>
            </div>
        </div>
        <div class="col-span-1 p-6 flex items-center justify-end text-neutral-400 text-base font-medium">
            <a href="{% url 'accounts:logout' %}"
                class="px-4 py-2 rounded-md bg-red-500 text-base text-neutral-300 font-medium flex items-center justify-center">
                Logout
            </a>
        </div>
    </div>

    <!-- Divider -->
    <div class="w-full h-[1.5px] bg-neutral-900/50 mt-5 mb-10"></div>

    <!-- Your videos and activities -->
    <div class="w-full space-y-10 px-10">
        <!-- Your activity -->
        <div class="w-full space-y-3">
            <h1 class="text-xl font-bold text-neutral-300">
                Your Activities
            </h1>

            <!-- Activities -->
            <div class="w-full flex-1 mt-5 px-4 py-5">
                {% for user_act in liked_videos %}
                <div class="w-full space-y-4">
                    <!-- <h1 class="text-xl font-bold text-neutral-200">
                        You Have Liked "<span class="text-red-500 text-2xl">{{user_act.count}}</span>" Videos Yet
                    </h1> -->
                    <div
                        class="w-full h-auto grid md:grid-cols-4 sm:grid-cols-3 grid-cols-2 md:gap-x-4 gap-x-2 gap-y-6">
                        <div
                            class="w-full h-auto rounded-full overflow-hidden px-3 py-1.5 text-base text-neutral-400 text-center bg-neutral-900/20 hover:bg-neutral-900/40 cursor-pointer ease-in-out duration-300">
                            <a href="{% url 'home:detail' user_act.id %}">
                                You liked 
                                "<span class="text-sm text-neutral-300">{{user_act.title}}</span>"
                                 video
                            </a>
                        </div>
                    </div>
                </div>
                {%empty%}
                <div class="w-full space-y-6 h-auto flex-col py-10 flex items-center justify-center">
                    <h1 class="text-3xl font-bold text-neutral-300">
                        You Have No Activity Yet!
                    </h1>
                </div>
                {% endfor %}
            </div>

        </div>
    </div>


</div>


{%endblock%}

templates/accounts/register.html
{% extends '../base.html'%}
{% load static %}
{%block titleblock%}Sign Up{%endblock%}
{%block bodyblock%}
<style>
    .form-text {
        display: none;
    }
</style>

<div class="w-full h-screen flex-1 flex items-center justify-center mt-10">
    <div class="w-[28%] h-auto py-10 px-8 rounded-xl border-2 border-neutral-900 shadow-md">
        <div class="space-y-2 mb-5">
            <h1 class="text-3xl font-bold text-neutral-100 mb-">Sign Up</h1>
            <p class="text-sm text-neutral-600 font-normal">
                Create a free account to get started!
            </p>
        </div>
        <form method="post" class="w-full">
            {% csrf_token %}
            {% for field in form %}
            <div class="w-full mb-4 relative">
                <label for="{{ field.id_for_label }}" class="text-base text-neutral-500 font-medium mb-2 block">
                    {{ field.label }}
                </label>
                {{field}}
            </div>
            {% endfor %}

            <button type="submit"
                class="w-full h-11 text-base font-semibold bg-red-600 text-neutral-50 mt-8 rounded-md">
                Sign Up
            </button>
            <p class="text-base text-neutral-600 font-normal mt-7 text-center">
                Already had an account?
                <a href="{% url 'accounts:login'%}"
                    class="text-decoration-none text-red-500 hover:text-red-600 ease-out duration-300">
                    Login
                </a>
            </p>
        </form>
    </div>
</div>

<script>


    document.addEventListener('DOMContentLoaded', function () {

        // Find the password input
        var first_name = document.querySelector('#id_first_name');
        var last_name = document.querySelector('#id_last_name');
        var email = document.querySelector('#id_email');
        var p1 = document.querySelector('#id_password1');
        var p2 = document.querySelector('#id_password2');
        first_name.placeholder='Enter your first name'
        last_name.placeholder='Enter your last name'
        email.placeholder = 'Enter your email'
        p1.placeholder = 'Enter password'
        p2.placeholder = 'Confirm password'
        email.type = 'email'
        email.className = 'w-full h-11 bg-neutral-950 outline-none px-4 text-base placeholder-neutral-700 font-normal rounded-md ring-1 ring-neutral-800 focus:ring-2 focus:ring-red-500 text-neutral-200'
        p1.className = 'w-full h-11 bg-neutral-950 outline-none px-4 text-base placeholder-neutral-700 font-normal rounded-md ring-1 ring-neutral-800 focus:ring-2 focus:ring-red-500 text-neutral-200'
        p2.className = 'w-full h-11 bg-neutral-950 outline-none px-4 text-base placeholder-neutral-700 font-normal rounded-md ring-1 ring-neutral-800 focus:ring-2 focus:ring-red-500 text-neutral-200'
        first_name.className = 'w-full h-11 bg-neutral-950 outline-none px-4 text-base placeholder-neutral-700 font-normal rounded-md ring-1 ring-neutral-800 focus:ring-2 focus:ring-red-500 text-neutral-200'
        last_name.className = 'w-full h-11 bg-neutral-950 outline-none px-4 text-base placeholder-neutral-700 font-normal rounded-md ring-1 ring-neutral-800 focus:ring-2 focus:ring-red-500 text-neutral-200'
    });
</script>



{%endblock%}