accounts/urls.py
from django.urls import path
from .views import RegisterView, UserLoginView, UserProfileView, UserLogoutView
app_name = 'accounts'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('profile/', UserProfileView.as_view(), name='profile'),
]

home/urls.py
from django.urls import path
from .views import HomeView, VideoDetailView, VideoListView, SearchView, LikeView, DislikeView, LikedVideosView, FilterView
app_name = 'home'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('video/', VideoListView.as_view(), name='video'),
    path('video/detail/<int:pk>', VideoDetailView.as_view(), name='detail'),
    path('search/', SearchView.as_view(), name='search'),
    path('like/<int:pk>/', LikeView.as_view(), name='like'),
    path('dislike/<int:pk>/', DislikeView.as_view(), name='dislike'),
    path('likedvideos/', LikedVideosView.as_view(), name='likedvideos'),
    path('filter/<str:genre>/', FilterView.as_view(), name='filter'),
]

videoplayer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('dashboard/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Add the following line to serve static files during development
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/videos/detail.html
{% extends '../base.html'%}
{% load static %}

{%block titleblock%}{{object.title}}{%endblock%}

<!-- 
    - Flowbite CSS 
-->
<link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.css" rel="stylesheet" />


{%block bodyblock%}


<div class="w-full h-auto flex-1 mt-5 px-4 py-5">
    <div class="grid grid-cols-3 gap-y-6">
        <!-- Video Play section -->
        <div class="col-span-2 lg:mr-20 mr-0 rounded-md space-y-7">
            <!-- Video section -->
            <div class="w-full h-auto rounded-md relative group">
                <video id="myVideo" autoplay loop class="w-full aspect-video rounded-md">
                    <source src="{{object.video_file.url}}" type="video/mp4">
                </video>
                <div
                    class="controls absolute bottom-0 left-0 w-full h-auto px-7 py-5 bg-gradient-to-t from-neutral-950/70 via-neutral-950/60 to-neutral-950/5 flex items-center justify-between opacity-0 group-hover:opacity-100 transition-all ease-in-out duration-300">
                    <div class="flex items-center gap-x-4">
                        <button id="skipBackwardButton" onclick="skipBackward()">
                            <i
                                class="fa-solid fa-backward text-neutral-50 text-2xl hover:scale-125 ease-in-out duration-300"></i>
                        </button>
                        <button id="playButton" onclick="playPause()">
                            <i
                                class="fa-solid fa-pause text-neutral-50 text-2xl hover:scale-125 ease-in-out duration-300"></i>
                        </button>
                        <button id="skipForwardButton" onclick="skipForward()">
                            <i
                                class="fa-solid fa-forward text-neutral-50 text-2xl hover:scale-125 ease-in-out duration-300"></i>
                        </button>
                        <div class="text-neutral-300 text-base font-normal">
                            <span id="currentTime">0:00</span> / <span id="duration">0:00</span>
                        </div>
                    </div>
                    <input type="range" id="volume" min="0" max="1" step="0.1"
                        class="w-auto h-[4px] bg-red-500 rounded-lg appearance-none cursor-pointer"
                        onchange="changeVolume()">
                </div>
            </div>

            <!-- Video actions -->
            <div class="w-full h-auto flex items-center justify-between px-3 pb-3.5 border-b border-neutral-900/50">
                <div class="flex items-center bg-neutral-900 rounded-md px-2">
                    {% if user.is_authenticated %}
                    <form action="{% url 'home:like' object.pk %}" method="POST">
                        {% csrf_token %}
                        <button type="submit"
                            class="text-neutral-300 text-xl py-1 px-2 border-r border-neutral-800 flex items-center justify-center gap-x-2">
                            <i class="fa-regular fa-thumbs-up"></i>
                            <span class="text-base">
                                {{object.like.count}}
                            </span>
                        </button>
                    </form>
                    {% else %}
                    <a href="{% url 'accounts:login' %}"
                        class="text-neutral-300 text-xl py-1 px-2 border-r border-neutral-800 flex items-center justify-center gap-x-2">
                        <i class="fa-regular fa-thumbs-up"></i>
                        <span class="text-base">
                            {{object.like.count}}
                        </span>
                    </a>
                    {% endif %}

                    <!-- Dislike button -->
                    {% if user.is_authenticated %}
                    <form action="{% url 'home:dislike' object.pk %}" method="POST">
                        {% csrf_token %}
                        <button type="submit"
                            class="text-neutral-300 text-xl py-1 px-2 border-l border-neutral-800 flex items-center justify-center gap-x-2">
                            <i class="fa-regular fa-thumbs-down"></i>
                            <span class="text-base">
                                {{object.dislike.count}}
                            </span>
                        </button>
                    </form>
                    {% else %}
                    <a href="{% url 'accounts:login' %}"
                        class="text-neutral-300 text-xl py-1 px-2 border-r border-neutral-800 flex items-center justify-center gap-x-2">
                        <i class="fa-regular fa-thumbs-down"></i>
                        <span class="text-base">
                            {{object.dislike.count}}
                        </span>
                    </a>
                    {% endif %}
                </div>
                <div>
                    <button
                        class="text-neutral-300 text-base py-1 px-2 bg-neutral-900 rounded-md  flex items-center justify-center gap-x-2">
                        <i class="fa-solid fa-share-nodes"></i>
                        <span class="text-sm">{{object.shares.count}}</span>
                    </button>
                </div>
            </div>

            <!-- Display Video comment section -->
            <div class="w-full h-auto space-y-3 text-neutral-500" id="comments">
                {% if object.comments %}
                {% for i in object.comments %}
                <div class="w-full flex items-start gap-x-2">
                    <img src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png"
                        alt="profile image" class="w-12 h-12 p-0.5 rounded-full object-cover object-center">
                    <div class="space-y-2">
                        <div class="space-y-0.5">
                            <h1 class="text-base font-semibold text-neutral-300">
                                {{i.user.get_full_name}}
                            </h1>
                            <p class="text-sm font-normal text-neutral-600">
                                {{i.created_at|timesince}}
                            </p>
                        </div>
                        <p class="text-sm font-normal">
                            {{ i.comment }}
                        </p>
                    </div>
                </div>
                {%endfor%}
                {% else %}
                <p class="text-neutral-500 font-medium text-base">
                    No comments yet!
                </p>
                {% endif %}
            </div>

        </div>

        <!-- Video detail section -->
        <div class="col-span-1 rounded-md space-y-6">

            <!-- Channel name -->
            <!-- <div class="w-full h-auto space-y-4 border-b border-neutral-900 pb-4">
                <h1 class="text-base font-semibold text-neutral-400">
                    Published by
                </h1>
                <div class="flex items-center gap-x-3">
                    <img src="https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=880&q=80"
                        alt="channel image" class="w-14 h-14 rounded-full">

                    <div>
                        <h1 class="text-xl text-neutral-300 font-bold">
                            Channel Name
                        </h1>
                        <h1 class="text-sm text-neutral-400">
                            Joined June 2023
                        </h1>
                    </div>
                </div>
            </div> -->

            <div class="space-y-3">
                <!-- Video title -->
                <h1 class="text-2xl text-neutral-300 font-bold">
                    {{object.title}}
                </h1>

                <div class="space-y-1 text-base text-neutral-500 font-normal">
                    <h6 class="">
                        Produced by: <span class="text-neutral-400 font-medium">{{object.producer}}</span>
                    </h6>
                    <h6 class="">
                        Genre: <span class="text-neutral-400 font-medium">{{object.genre}}</span>
                    </h6>
                    <div class="bg-neutral-900 text-sm text-red-500 rounded-md w-fit px-2 py-1">
                        {{object.age_rating}} Rated
                    </div>
                </div>

                <!-- Video Description -->
                <p class="text-base text-neutral-500 font-normal line-clamp-4 text-overflow-ellipsis">
                    {{object.description}}
                </p>

            </div>

            <!-- Comment section -->
            <div class="w-full h-auto space-y-4">
                <h1 class="text-base font-semibold text-neutral-400">
                    Write a comment
                </h1>
                <form action="" method="post">
                    <div class="flex flex-col gap-y-5">
                        {% csrf_token %}
                        {{form.as_p}}

                        <!-- Button -->
                        <div class="w-full h-auto flex items-center">
                            {% if user.is_authenticated %}
                            <button type="submit"
                                class="bg-red-500 text-neutral-950 font-medium text-base flex items-center justify-center px-5 py-2 rounded-md hover:bg-red-600 ease-in-out duration-300">
                                Post Comment
                            </button>
                            {% else %}
                            <a href="{% url 'accounts:login' %}"
                                class="bg-red-500 text-neutral-950 font-medium text-base flex items-center justify-center px-5 py-2 rounded-md hover:bg-red-600 ease-in-out duration-300">
                                Log in to post comment
                            </a>
                            {% endif %}
                        </div>
                    </div>
                </form>

            </div>

        </div>

    </div>

    <!-- Separator -->
    <!-- <hr class="my-14 border-b border-neutral-900"> -->

</div>


{%block scriptblock%}
<!-- 
    - Flowbite Js Link 
-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"></script>


<!-- For video controls -->

<script>
    const video = document.getElementById('myVideo');
    const playButton = document.getElementById('playButton');
    const skipBackwardButton = document.getElementById('skipBackwardButton');
    const skipForwardButton = document.getElementById('skipForwardButton');
    // const skipBackwardButton = document.querySelector('button:nth-child(1)'); // Select the first button for skip backward
    // const skipForwardButton = document.querySelector('button:nth-child(3'); // Select the third button for skip forward
    const volumeSlider = document.getElementById('volume');
    const currentTimeSpan = document.getElementById('currentTime');
    const durationSpan = document.getElementById('duration');

    video.addEventListener('loadedmetadata', function () {
        durationSpan.textContent = formatTime(video.duration);
    });


    function playPause() {
        if (video.paused) {
            video.play();
            playButton.classList.remove('play-icon');
            playButton.classList.add('pause-icon');
            playButton.innerHTML = '<i class="fas fa-pause  text-neutral-50 text-2xl hover:scale-125 ease-in-out duration-300"></i>';
        } else {
            video.pause();
            playButton.classList.remove('pause-icon');
            playButton.classList.add('play-icon');
            playButton.innerHTML = '<i class="fas fa-play  text-neutral-50 text-2xl hover:scale-125 ease-in-out duration-300"></i>';
        }
    }

    // Skips the video backward by 10 seconds.
    function skipBackward() {
        video.currentTime = Math.max(0, video.currentTime - 5);
    }

    function skipForward() {
        video.currentTime = Math.max(0, video.currentTime + 5);
    }

    function changeVolume() {
        video.volume = volumeSlider.value;
    }

    function formatTime(time) {
        const minutes = Math.floor(time / 60);
        const seconds = Math.floor(time % 60);
        return `${minutes}:${seconds < 10 ? '0' : ''}${seconds}`;
    }

    video.addEventListener('timeupdate', function () {
        currentTimeSpan.textContent = formatTime(video.currentTime);
    });
</script>


{%endblock%}

{%endblock%}

templates/videos/filter.html
{% load static %}

<div
    class="w-full flex items-center justify-between gap-4 bg-neutral-900/30 rounded-md text-neutral-500 text-base font-medium px-4 py-5">
    <!-- Showing results -->
    <div class="flex items-center gap-2 text-neutral-400">
        Showing <span class="text-red-500">" {{videos.count}} "</span> results
    </div>

    <button id="multiLevelDropdownButton" data-dropdown-toggle="multi-dropdown"
        class="text-neutral-200 bg-red-500/20 hover:bg-red-600/30 outline-none font-medium rounded-md text-sm px-5 py-2.5 text-center inline-flex items-center ease-in-out duration-500"
        type="button">Sort By Category
        <svg class="w-2.5 h-2.5 ms-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
            viewBox="0 0 10 6">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                d="m1 1 4 4 4-4" />
        </svg>
    </button>

    <!-- Dropdown menu -->
    <div id="multi-dropdown" class="z-10 hidden bg-neutral-800 rounded-md shadow-md min-w-40 max-w-52 w-fit">
        <ul class="text-sm text-neutral-300 rounded-md overflow-hidden" aria-labelledby="multiLevelDropdownButton">
            {% if filter_videos is None %}
            <li>
                <a href="{% url 'home:video' %}" class="block px-4 py-2 hover:bg-neutral-900">All</a>
            </li>
            {% else %}
            {% for genre in filter_videos %}
            <li>
                <a href="{% url 'filter' genre.genre %}" class="block px-4 py-2 hover:bg-neutral-900">
                    {{ genre.genre}}
                </a>
            </li>
            {% endfor %}
            {% endif %}
        </ul>
    </div>

</div>

templates/videos/video.html
{% extends '../base.html'%}
{% load static %}

{%block titleblock%}Videos{%endblock%}

<!-- 
    - Flowbite CSS 
-->
<link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.css" rel="stylesheet" />


{%block bodyblock%}


<div class="w-full h-auto flex-1 px-4 py-5">
    <div class="w-full space-y-8">
        <!-- Filter section -->
        {% include 'videos/filter.html' %}

        <!-- Video Card section -->
        {% include 'videos/videocard.html' %}
    </div>

</div>


{%block scriptblock%}
<!-- 
    - Flowbite Js Link 
-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"></script>

{%endblock%}

{%endblock%}

templates/videos/videocard.html
{% load static %}

<div class="w-full h-auto grid md:grid-cols-4 sm:grid-cols-3 grid-cols-2 md:gap-x-4 gap-x-2 gap-y-6">

    {% for video in videos %}
    <div
        class="w-full h-auto rounded-md rounded-md overflow-hidden hover:bg-neutral-900/20 cursor-pointer ease-in-out duration-300">
        <a href="{% url 'home:detail' pk=video.pk %}">
            <div class="w-full h-auto rounded-md overflow-hidden">
                <img src="{{video.video_thumbnail.url}}" alt="video thumbnail"
                    class="w-full aspect-video object-cover object-center transition-all ease-in-out duration-300">
                <div class="px-2 py-3 space-y-2">
                    <h1 class="text-xl font-bold text-neutral-300 cursor-pointer line-clamp-2 text-overflow-ellipsis">
                        {{video.title}}
                    </h1>
                    <div class="w-full flex items-center justify-between gap-x-3">
                        <h6 class="text-sm text-neutral-500 font-normal">
                            Produced by: {{video.producer}}
                        </h6>
                        <div class="bg-neutral-900 text-sm text-red-500 rounded-md w-fit px-2 py-1">
                            {{video.age_rating}}
                        </div>
                    </div>
                </div>
            </div>
        </a>
    </div>
    {%empty%}
    <div class="w-full col-span-4 h-auto flex items-center justify-center">
        <h1 class="text-3xl font-bold text-neutral-300">
            No Videos Found Yet (` ; `)
        </h1>
    </div>
    {% endfor %}
</div>