accounts/urls.py
from django.urls import path
from .views import RegisterView, UserLoginView, UserProfileView, UserLogoutView
app_name = 'accounts'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('profile/', UserProfileView.as_view(), name='profile'),
]

home/urls.py
from django.urls import path
from .views import HomeView, VideoDetailView, VideoListView, SearchView, LikeView, DislikeView, LikedVideosView, FilterView
app_name = 'home'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('video/', VideoListView.as_view(), name='video'),
    path('video/detail/<int:pk>', VideoDetailView.as_view(), name='detail'),
    path('search/', SearchView.as_view(), name='search'),
    path('like/<int:pk>/', LikeView.as_view(), name='like'),
    path('dislike/<int:pk>/', DislikeView.as_view(), name='dislike'),
    path('likedvideos/', LikedVideosView.as_view(), name='likedvideos'),
    path('filter/<str:genre>/', FilterView.as_view(), name='filter'),
]

videoplayer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('dashboard/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Add the following line to serve static files during development
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <meta name="viewport" content="width=device-width, initial-scale=0.9" />
    <!-- 
        - Tailwind CSS Link
     -->
    <script src="https://cdn.tailwindcss.com"></script>

    <!-- 
        - Google Fonts ( Open Sans )
     -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap"
        rel="stylesheet">

    <!-- 
        - Custom CSS Link
     -->
    <link rel="stylesheet" href="{% static 'css/style.css'%}">

    <!-- 
        - Font Awesome Link
     -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
        integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!-- 
        - SwiperJs CSS Link
     -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />

    <title>{%block titleblock%}{%endblock%} | GokuFlix</title>
</head>

<body>
    <!-- loader will be here -->

    <div class="w-full min-h-screen bg-neutral-950">
        <div class="w-full min-h-screen flex flex-col">

            <!-- Navbar Section -->
            {%include 'navbar.html'%}

            {%include 'message.html'%}


            {%block bodyblock%}

            {%endblock%}

            {%block scriptblock%}

            {%endblock%}

            <!-- footer Section -->
            <!-- footer will be here -->
        </div>
    </div>
    
    <!-- 
        - SwiperJs JS Link
     -->
    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>


    <script>
        var swiper = new Swiper(".mySwiper", {
            slidesPerView: 1,
            spaceBetween: 10,
            loop: false,
            // autoplay: {
            //     delay: 3000,
            //     disableOnInteraction: false,
            // },
            navigation: {
                nextEl: ".swiper-button-next",
                prevEl: ".swiper-button-prev",
            },
            breakpoints: {
                640: {
                    slidesPerView: 2,
                    spaceBetween: 20,
                },
                768: {
                    slidesPerView: 4,
                    spaceBetween: 10,
                },
                1024: {
                    slidesPerView: 6,
                    spaceBetween: 10,
                },
            },
        });
    </script>

</body>

</html>

templates/message.html
{% for message in messages %}
{% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
<!-- sweetalert js -->
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<style>
    .small-popup {
        width: 300px;
    }

    .small-title {
        font-size: 16px;
    }
</style>
<script>
    var m = "{{ message }}";
    Swal.fire({
        icon: "success",
        title: m,
        showConfirmButton: false,
        timer: 2000,
        customClass: {
            popup: 'small-popup',
            title: 'small-title'
        }
    });
</script>
{% elif message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
<!-- sweetalert js -->
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<style>
    .small-popup {
        width: 300px;
    }

    .small-title {
        font-size: 16px;
    }
</style>
<script>
    var m = "{{ message }}";
    Swal.fire({
        icon: "info",
        title: m,
        showConfirmButton: false,
        timer: 2000,
        customClass: {
            popup: 'small-popup',
            title: 'small-title'
        }
    });
</script>
{% else %}
<!-- sweetalert js -->
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<style>
    .small-popup {
        width: 300px;
    }

    .small-title {
        font-size: 16px;
    }
</style>
<script>
    var m = "{{ message }}";
    Swal.fire({
        icon: "error",
        title: m,
        showConfirmButton: false,
        timer: 2000,
        customClass: {
            popup: 'small-popup',
            title: 'small-title'
        }
    });
</script>
{% endif %}
{% endfor %}

templates/navbar.html
{% load static %}


<nav id="navbar"
    class="relative flex flex-col md:items-center bg-neutral-900 shadow h-auto py-4 md:flex-row lg:items-end justify-between px-10 gap-7 md:gap-0 z-30">
    <!-- Logo section -->
    <div class="flex items-center">
        <a href="/" class="text-decoration-none text-xl font-medium text-neutral-800 md:mb-2 mb-0 mr-16 d-flex">
            <h1 class="tex-xl font-bold text-red-500 uppercase">
                Gokuflix
            </h1>
        </a>
    </div>

    <!-- Nav items & login events -->
    <div id="navItems"
        class="flex-1 hidden md:flex flex-col md:flex-row gap-x-5 gap-y-2 md:items-center md:p-0 sm:p-4 p-4 justify-between md:bg-transparent bg-neutral-800 md:shadow-none sm:shadow-md shadow-md rounded-md">
        <!-- Nav items -->
        <ul
            class="list-none flex md:items-center sm:items-start items-start gap-x-5 gap-y-1 flex-wrap md:flex-row sm:flex-col flex-col">
            <li>
                <a href="{% url 'home:video' %}"
                    class="text-decoration-none text-base font-medium text-neutral-400 hover:text-red-500 ease-in-out duration-300">
                    Movies
                </a>
            </li>
            {% if request.user.is_authenticated %}
            <li>
                <a href="{% url 'home:likedvideos' %}"
                    class="text-decoration-none text-base font-medium text-neutral-400 hover:text-red-500 ease-in-out duration-300">
                    Liked
                </a>
            </li>
            {% endif %}
        </ul>

        <div class="flex items-center gap-x-7 gap-y-5 flex-wrap">
            <!-- Search -->
            <form action="{% url 'home:search' %}">
                {% csrf_token %}
                <div
                    class="w-[350px] h-10 md:bg-neutral-800 bg-neutral-900 text-base font-medium text-neutral-300 flex items-center border lg:border-neutral-800 border-neutral-900 rounded-md overflow-hidden">
                    <input type="text" name="search" placeholder="Search for movies..."
                        class="w-[85%] bg-transparent h-full px-4 outline-none placeholder-neutral-500">
                    <button
                        class="bg-transparent w-[15%] h-full border-l-2 lg:border-neutral-700/60 border-neutral-800/60 text-base text-neutral-400 hover:text-red-500 ease-in-out duration-300 flex items-center justify-center">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </form>

            {% if request.user.is_authenticated %}
            <!-- Profile image -->
            <a href="{% url 'accounts:profile' %}" class="text-base font-medium text-neutral-400">
                <img src="{{request.user.get_profile_pic}}" alt="profile image"
                    class="w-10 h-10 p-0.5 rounded-full object-cover object-center border border-neutral-800/90">
            </a>
            {% else %}
            <a href="{% url 'accounts:login' %}"
                class="w-fit bg-red-700 px-4 py-2 rounded-full text-sm font-medium text-neutral-200 hover:bg-red-600 ease-in-out duration-500">
                Create Account
            </a>
            {% endif %}
        </div>

    </div>
    <button id="btnToggle" class="block md:hidden absolute md:top-6 top-4 right-10 text-neutral-400">
        <i class="fas fa-bars text-2xl pb-2"></i>
    </button>
</nav>

<script>
    const btnToggle = document.getElementById('btnToggle');
    const nav = document.getElementById('navItems');

    // Create a new element
    const iconElement = document.createElement('i');

    // Click button click event listener
    btnToggle.addEventListener('click', () => {
        nav.classList.toggle('flex');
        nav.classList.toggle('hidden');

        if (nav.classList.contains('flex')) {
            // Set the inner HTML of the element to the desired HTML snippet
            btnToggle.innerHTML = '<i class="fas fa-close text-2xl"></i>';

            // Append the new element to an existing element in the DOM (e.g., with id 'container')
            document.getElementById('btnToggle').appendChild(iconElement);

        } else {
            // Set the inner HTML of the element to the desired HTML snippet
            btnToggle.innerHTML = '<i class="fas fa-bars text-2xl"></i>';

            // Append the new element to an existing element in the DOM (e.g., with id 'container')
            document.getElementById('btnToggle').appendChild(iconElement);
        }
    })
</script>